version: '3.8'

services:
  audio-to-viseme:
    build:
      context: .
      dockerfile: Dockerfile.cpu
    volumes:
      - .:/app
      - ./results:/app/results
    command: test-audio.wav results/test-output.json --whisper-model base 